# -*- indent-tabs-mode: nil; c-basic-offset: 4; tab-width: 4;-*-
image: debian:testing

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CXXFLAGS: "-O3"
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

openmpi:
    stage: build
    script:
        - apt update -qq && apt install -qq -y --no-install-recommends libopenmpi-dev openmpi-bin cmake make g++ libboost-serialization-dev
        - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3
        - cd test
        - mkdir build && cd build
        - export MPI_OVERSUBSCRIBE="--oversubscribe"
        - cmake ..
        - make
        - ctest --output-on-failure

openmpi-clang:
    stage: build
    script:
        - apt update -qq && apt install -qq -y --no-install-recommends libopenmpi-dev openmpi-bin cmake make clang libstdc++-11-dev libboost-serialization-dev
        - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3
        - cd test
        - mkdir build && cd build
        - export MPI_OVERSUBSCRIBE="--oversubscribe"
        - clang++ --version
        - mpirun --version
        - CXX=clang++ cmake ..
        - make
        - ctest --output-on-failure

ompi-clang-tidy:
    stage: build
    script:
        - apt update -qq && apt install -qq -y --no-install-recommends libopenmpi-dev openmpi-bin clang libstdc++-11-dev clang-tidy cmake make libboost-serialization-dev
        - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3
        - cd test
        - mkdir build && cd build
        - export MPI_OVERSUBSCRIBE="--oversubscribe"
        - clang++ --version
        - clang-tidy --version
        - CXX=clang++ cmake .. -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=*,-bugprone-exception-escape,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-hicpp-no-array-decay,-google-runtime-references,-fuchsia-default-arguments-calls,-fuchsia-statically-constructed-objects,-fuchsia-trailing-return,-fuchsia-overloaded-operator,-cppcoreguidelines-pro-type-vararg,-hicpp-vararg,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers,-cppcoreguidelines-macro-usage,-cppcoreguidelines-avoid-non-const-global-variables,-modernize-use-trailing-return-type,-llvmlibc-implementation-in-namespace,-llvmlibc-callee-namespace,-llvmlibc-restrict-system-libc-headers,-cert-err58-cpp;--warnings-as-errors=*"
        - make VERBOSE=1
        - ctest --output-on-failure

ompi-clang-tidy-dev:
    image: silkeh/clang:dev
    stage: build
    script:
        - apt update -qq && apt install -qq -y --no-install-recommends libopenmpi-dev openmpi-bin clang `#libstdc++-dev` clang-tidy cmake make libboost-serialization-dev
        - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3
        - cd test
        - mkdir build && cd build
        - export MPI_OVERSUBSCRIBE="--oversubscribe"
        - clang++ --version
        - clang-tidy --version
        - CXX=clang++ cmake .. -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=*,-altera-id-dependent-backward-branch,-altera-unroll-loops,-altera-struct-pack-align,-bugprone-exception-escape,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-hicpp-no-array-decay,-google-runtime-references,-fuchsia-default-arguments-calls,-fuchsia-statically-constructed-objects,-fuchsia-trailing-return,-fuchsia-overloaded-operator,-cppcoreguidelines-pro-type-vararg,-hicpp-vararg,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers,-readability-identifier-length,-cppcoreguidelines-macro-usage,-cppcoreguidelines-avoid-non-const-global-variables,-modernize-use-trailing-return-type,-llvmlibc-implementation-in-namespace,-llvmlibc-callee-namespace,-llvmlibc-restrict-system-libc-headers,-cert-err58-cpp;--warnings-as-errors=*"
        - make VERBOSE=1
        - ctest --output-on-failure

#        - export CC=mpicc
#        - export CXX=mpic++
#        - export CCFLAGS="`mpic++ --showme:incdirs`"
#        - export CXXFLAGS="`mpic++ --showme:incdirs`"
#        - echo $CXXFLAGS

#openmpi-valgrind:
#    stage: build
#    script:
#        - apt update  -qq
#        - apt install -qq -y --no-install-recommends libopenmpi-dev openmpi-bin cmake make g++ libboost-serialization-dev valgrind
#        - cd ..
#        - ln -s boost-mpi3 mpi3
#        - cd mpi3/test
#        - mkdir build
#        - cd build
#        - export MPI_OVERSUBSCRIBE=--oversubscribe
#        - export VALGRIND_EXE="valgrind --suppressions=communicator_main.cpp.openmpi.supp"
#        - cmake ..
#        - pwd
#        - mpirun --version
#        - make -j 4
#        - ctest -VV --output-on-failure

mpich:
    stage: build
    script:
        - apt update -qq && apt install -qq -y --no-install-recommends libmpich-dev mpich cmake make g++ libboost-serialization-dev
        - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3
        - cd test
        - mkdir build && cd build
        - export MPI_OVERSUBSCRIBE=""
        - cmake ..
        - make
        - ctest --output-on-failure

mpich-valgrind:
    stage: build
    script:
        - apt update -qq && apt install -qq -y --no-install-recommends libmpich-dev mpich cmake make g++ libboost-serialization-dev valgrind
        - mpirun --version
        - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3/test
        - mkdir build && cd build
        - export MPI_OVERSUBSCRIBE=""
        - export VALGRIND_EXE="valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all --error-exitcode=1"
        - cmake ..
        - make
        - ctest --output-on-failure

qmcpack-g++:
    stage: test
    script:
        - apt-get -qq update && apt-get -qq install --no-install-recommends -y libblas-dev liblapack-dev libfftw3-dev libboost-serialization-dev libopenmpi-dev gfortran g++ cmake make git ca-certificates   numdiff  python3 python3-numpy python3-h5py python3-mpi4py python3-scipy libxml2-dev libhdf5-dev
        - git clone https://github.com/QMCPACK/qmcpack.git
        - cd qmcpack
        - git config --global user.email "alfredo.correa@gmail.com" && git config --global user.name "Alfredo Correa"
        - git rm -r external_codes/mpi_wrapper/mpi3 && git commit -m "remove mpi3 subtree"
        - git subtree add --squash -P external_codes/mpi_wrapper/mpi3 https://gitlab.com/correaa/boost-mpi3.git $CI_COMMIT_BRANCH
        - cd build
        - cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=1 -DBUILD_PPCONVERT=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=Debug -DMPIEXEC_PREFLAGS="--allow-run-as-root;--bind-to;none" .. #-DCMAKE_CXX_FLAGS="-Werror"
        - make # afqmc test_afqmc_matrix test_afqmc_numerics test_afqmc_slaterdeterminantoperations test_afqmc_walkers test_afqmc_hamiltonians test_afqmc_hamiltonian_operations test_afqmc_phmsd test_afqmc_wfn_factory test_afqmc_prop_factory test_afqmc_estimators qmc-afqmc-performance
        - ctest -R afqmc     --output-on-failure

qmcpack-cuda-11.2-compileonly:
    image: nvidia/cuda:11.2.0-devel
    stage: test
    script:
        - export DEBIAN_FRONTEND=noninteractive
        - apt-get -qq update && apt-get -qq install --no-install-recommends -y libblas-dev liblapack-dev libfftw3-dev libboost-serialization-dev libopenmpi-dev gfortran g++ make git ca-certificates numdiff python3 python3-numpy python3-h5py python3-mpi4py python3-scipy libxml2-dev libhdf5-dev wget
        - wget https://cmake.org/files/v3.21/cmake-3.21.3-linux-x86_64.sh --no-verbose # following https://askubuntu.com/a/865294/15943
        - mkdir /opt/cmake
        - sh cmake-3.21.3-linux-x86_64.sh --skip-license --prefix=/opt/cmake
        - ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
        - cmake --version
        - git clone https://github.com/QMCPACK/qmcpack.git
        - cd qmcpack
        - git config --global user.email "alfredo.correa@gmail.com" && git config --global user.name "Alfredo Correa"
        - git rm -r external_codes/mpi_wrapper/mpi3 && git commit -m "remove mpi3 subtree"
        - git subtree add --squash -P external_codes/mpi_wrapper/mpi3 https://gitlab.com/correaa/boost-mpi3.git $CI_COMMIT_BRANCH
        - cd build
        - cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=1 -DBUILD_PPCONVERT=1 -DQMC_CXX_STANDARD=17 -DENABLE_CUDA=1 ..
        - make qmcpack afqmc test_afqmc_matrix test_afqmc_numerics test_afqmc_slaterdeterminantoperations test_afqmc_walkers test_afqmc_hamiltonians test_afqmc_hamiltonian_operations test_afqmc_phmsd test_afqmc_wfn_factory test_afqmc_prop_factory test_afqmc_estimators qmc-afqmc-performance

qmcpack-cuda-11.4-compileonly:
    image: nvidia/cuda:11.4.0-devel
    stage: test
    script:
        - export DEBIAN_FRONTEND=noninteractive
        - apt-get -qq update && apt-get -qq install --no-install-recommends -y libblas-dev liblapack-dev libfftw3-dev libboost-serialization-dev libopenmpi-dev gfortran g++ make git ca-certificates numdiff python3 python3-numpy python3-h5py python3-mpi4py python3-scipy libxml2-dev libhdf5-dev wget
        - wget https://cmake.org/files/v3.21/cmake-3.21.3-linux-x86_64.sh --no-verbose # following https://askubuntu.com/a/865294/15943
        - mkdir /opt/cmake
        - sh cmake-3.21.3-linux-x86_64.sh --skip-license --prefix=/opt/cmake
        - ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
        - cmake --version
        - git clone https://github.com/QMCPACK/qmcpack.git
        - cd qmcpack
        - git config --global user.email "alfredo.correa@gmail.com" && git config --global user.name "Alfredo Correa"
        - git rm -r external_codes/mpi_wrapper/mpi3 && git commit -m "remove mpi3 subtree"
        - git subtree add --squash -P external_codes/mpi_wrapper/mpi3 https://gitlab.com/correaa/boost-mpi3.git $CI_COMMIT_BRANCH
        - cd build
        - cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=1 -DBUILD_PPCONVERT=1 -DQMC_CXX_STANDARD=17 -DENABLE_CUDA=1 ..
        - make qmcpack afqmc test_afqmc_matrix test_afqmc_numerics test_afqmc_slaterdeterminantoperations test_afqmc_walkers test_afqmc_hamiltonians test_afqmc_hamiltonian_operations test_afqmc_phmsd test_afqmc_wfn_factory test_afqmc_prop_factory test_afqmc_estimators qmc-afqmc-performance

inq-g++-latest:
    stage: test
    script:
        - apt-get update && apt-get install --no-install-recommends -y --quiet libblas-dev liblapack-dev libfftw3-dev libboost-filesystem-dev libboost-serialization-dev libopenmpi-dev gfortran g++ cmake pkg-config make git ca-certificates
        - git clone https://gitlab.com/npneq/inq.git --recurse-submodules
        - cd inq
        - cd external_libs/mpi3
        - git checkout $CI_COMMIT_BRANCH
        - cd ../..
        - mkdir build && cd build
        - ../configure --prefix=$HOME
        - make
        - make install
        - ctest --output-on-failure

inq-cuda-11.2-compileonly:
    image: nvidia/cuda:11.2.0-devel
    stage: test
    script:
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update && apt-get install --no-install-recommends -y --quiet libblas-dev liblapack-dev libfftw3-dev libboost-filesystem-dev libboost-serialization-dev libopenmpi-dev gfortran g++ cmake pkg-config make git ca-certificates
      - git clone https://gitlab.com/npneq/inq.git --recurse-submodules
      - cd inq
      - cd external_libs/mpi3
      - git checkout $CI_COMMIT_BRANCH
      - cd ../..
      - mkdir build && cd build
      - /usr/local/cuda/bin/nvcc -V
      - CUDACXX=/usr/local/cuda/bin/nvcc CUDA_ARCH_OVERRIDE=1 ../configure --prefix=$HOME --enable-cuda --with-cuda-prefix=/usr/local/cuda
      - make silicon

inq-cuda-11.4-compileonly:
    image: nvidia/cuda:11.4.0-devel
    stage: test
    script:
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update && apt-get install --no-install-recommends -y --quiet libblas-dev liblapack-dev libfftw3-dev libboost-filesystem-dev libboost-serialization-dev libopenmpi-dev gfortran g++ cmake pkg-config make git ca-certificates
      - git clone https://gitlab.com/npneq/inq.git --recurse-submodules
      - cd inq
      - cd external_libs/mpi3
      - git checkout $CI_COMMIT_BRANCH
      - cd ../..
      - mkdir build && cd build
      - /usr/local/cuda/bin/nvcc -V
      - CUDACXX=/usr/local/cuda/bin/nvcc CUDA_ARCH_OVERRIDE=1 ../configure --prefix=$HOME --enable-cuda --with-cuda-prefix=/usr/local/cuda
      - make silicon

inq-nvcc-ompi:
    stage: test
    tags:
        - cuda_gpu
    script:
        - export PREFIX=`mktemp -d`
        - git clone https://gitlab.com/npneq/inq.git --recurse-submodules
        - cd inq
        - cd external_libs/mpi3
        - git checkout $CI_COMMIT_BRANCH
        - cd ../..
        - mkdir build && cd build
        - CUDACXX=/usr/local/cuda/bin/nvcc ../configure --prefix=$PREFIX --enable-cuda --disable-debug --with-cuda-prefix=/usr/local/cuda
        - make -j8
        - make -j8 install
        - ctest --output-on-failure --timeout 600
        - cd src; INQ_EXEC_ENV="mpirun --oversubscribe -np 4" ctest --output-on-failure --timeout 600; cd ..
        - rm -rf $PREFIX

openmpi-icpc-runner:
    stage: test
    tags:
        - cuda_gpu
    script:
        - cd .. && ln -s boost-mpi3 mpi3 && cd mpi3/test
        - mkdir build && cd build
        - CXX=/opt/intel/oneapi/compiler/2021.2.0/linux/bin/intel64/icpc cmake ..
        - mpirun --version
        - make VERBOSE=1
        - ctest --output-on-failure --timeout 120
