#  /* -*- indent-tabs-mode: nil; c-basic-offset: 4; tab-width: 4;-*- */
#required packages:
#    - time apt update -qq
#    - time apt install --no-install-recommends -y -qq ssh g++ gfortran clang autoconf make automake libgsl-dev libblas-dev liblapack-dev libfftw3-dev libxc-dev libopenmpi-dev openmpi-bin libboost-all-dev
#    - time apt install --no-install-recommends -y -qq nvidia-cuda-toolkit nvidia-cuda-dev nvidia-smi
#  CXX: "mpic++"
#  CMAKE_CXX_COMPILER: "mpic++"

image: debian:testing

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CXXFLAGS: "-O3"
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

mpich:
    stage: build
    script:
        - apt update  -qq
        - apt install -qq -y --no-install-recommends libopenmpi-dev openmpi-bin cmake make g++ libboost-all-dev
        - cd ..
        - ln -s boost-mpi3 mpi3
        - cd mpi3
        - cd test
        - ls
        - mkdir build
        - cd build
        - ls
        - ls ../
        - ls ../../
        - cmake ..
        - pwd
        - mpirun --version
        - make
        - ctest

